from django.db import models

class Match(models.Model):
	atp = models.IntegerField()
	location = models.CharField(max_length = 200)
	tournament = models.CharField(max_length = 200)
	date = models.CharField(max_length = 200)
	series = models.CharField(max_length = 200)
	court = models.CharField(max_length = 200)
	surface = models.CharField(max_length = 200)
	round = models.CharField(max_length = 200)
	bestof = models.IntegerField()
	winner = models.CharField(max_length = 200)
	loser = models.CharField(max_length = 200)
	wrank = models.IntegerField()
	lrank = models.IntegerField()
	wpts = models.IntegerField()
	lpts = models.IntegerField()
	w1 = models.IntegerField()
	l1 = models.IntegerField()
	w2 = models.IntegerField()
	l2 = models.IntegerField()
	w3 = models.IntegerField()
	l3 = models.IntegerField()
	w4 = models.IntegerField()
	l4 = models.IntegerField()
	w5 = models.IntegerField()
	l5 = models.IntegerField()
	wsets = models.IntegerField()
	lsets = models.IntegerField()
	comment = models.CharField(max_length = 200)
	b365w = models.FloatField()
	b365l = models.FloatField()
	exw = models.FloatField()
	exl = models.FloatField()
	lbw = models.FloatField()
	lbl = models.FloatField()
	psw = models.FloatField()
	psl = models.FloatField()
	sjw = models.FloatField()
	sjl = models.FloatField()
	maxw = models.FloatField()
	maxl = models.FloatField()
	avgw = models.FloatField()
	avgl = models.FloatField()
# Create your models here.
